### ISSUE TITLE
Can Tachyon be run without Lamda and on our own server with Tachyon's Docker Image

### ISSUE THREAD

**Issue by xianx** [humanmade/tachyon#106]
Is it possible to run Tachyon without Lamda and within our own server with Tachyon's Docker Image https://hub.docker.com/r/humanmade/tachyon

**Comment by rmccue** [comment]
Sure, you can run it however you want.

Please note our support policy though: https://engineering.hmn.md/projects/support/ - we are unable to provide detailed further support on running or scaling Tachyon outside of the recommended setup in Lambda.
