### ISSUE TITLE
question: architectural option

### ISSUE THREAD

**Issue by alsguimaraes** [humanmade/tachyon#116]
I think it would be nice if tachyon also supported [tachyon-edge architecture](https://github.com/spiritedmedia/tachyon-edge/raw/master/screenshot.png): CloudFront and LambdaEdge origin request event, without API Gateway.

I would like to know wheter you would be willing to accept a PR to enable tachyon to be manually deployed in such fashion (without the save resized to S3)?

Let me know if you are interested, and I will implement and add some specific documentation to allow that type of deployment.

**Comment by roborourke** [comment]
Hey @alsguimaraes.

I think part of the benefit of the current system is _not_ having to save any image other than the original to S3 given that a lot of those files wouldn't get used again (I'm thinking of cropping and generating previews).

Using lambda@edge on origin request is a nice idea but I'm not sure how it could be achieved without saving resized images to S3? I've only tinkered with lambda@edge a little bit so might be missing something.

Have you found it's more cost effective to run tachyon this way without API Gateway?

**Comment by roborourke** [comment]
And to answer your question with regards to a pull request I think we'd be happy to link out to tachyon-edge for the time being but we couldn't really take on supporting that option unless we decided to adopt that approach for our own infrastructure.

**Comment by alsguimaraes** [comment]
Submitted PR #122
