### ISSUE TITLE
Support upscaling images that are too small

### ISSUE THREAD

**Issue by johnbillion** [humanmade/tachyon#132]
As discussed on Ryan's office hours call today, given a registered image size in WordPress which sets the `$crop` parameter to true, Tachyon will not upscale an image to fit that size if either the original width or height are too small.

This matches the behaviour of WordPress core (tested on a site with Imagick) but may not be desirable. I think the expectation is that when registering an image size with `$crop` set to true and using Tachyon that the image will always be that exact size, including being upscaled as necessary.

The end result of the current behaviour is if you're displaying a grid of images with a fixed width and height but one or more images are too small, the grid layout will be broken because the aspect ratio of the images that are too small will not match the others.

**Comment by roborourke** [comment]
We intentionally got rid of this behaviour a few years ago to match core behaviour in the tachyon-plugin repo. The end result is terrible looking images, particularly when WP can request large upscaled sizes for `srcset` attributes. You can read some background here https://github.com/humanmade/tachyon-plugin/issues/48

We could maybe allow for overriding this but you have CSS options too, for example using `object-fit: cover;` that you could explore.

Alternatively it could be worth exploring ways to prevent uploads that are too small. That could be achieved for featured images relatively easily using something like the publication checklist plugin but would be harder to apply those rules more broadly.

**Comment by johnbillion** [comment]
Thanks for the history, that's interesting and good to know. An override would be good but I think this can also be solved editorially, so let's close this off.
