### ISSUE TITLE
Slow Performance on large crops

### ISSUE THREAD

**Issue by EffakT** [humanmade/tachyon#140]
Currently using Tachyon 2.4.0.
Occurs in both Lamba and Docker.

We have a JPG file that is 14176x6132.
Loading this image with "?w=1600&h=600" we get a TTFB of 1s
Loading this image with "?crop=2437px,0px,10095px,5678px&w=1600&h=600". We get a TTFB of around 4s.

As soon as we add the "?crop=" param, the TTFB increases by just over 3s.

Is this expected behaviour? or is there any way to improve performance?

**Comment by joehoyle** [comment]
Hmm I've not seen that before. It could depend on how many resources you are giving Lambda though. The TTFB is likely to linearly map to memory limit you provide the Lambda function (as that also scales CPU linearly too).
