### ISSUE TITLE
Circular dependency warnings on Node 14

### ISSUE THREAD

**Issue by jerico** [humanmade/tachyon#148]
Tachyon currently has dependency on [aws-xray-sdk-core@2.4.0](https://www.npmjs.com/package/aws-xray-sdk-core/v/2.4.0) which depends on winston@2.4.4 which has an issue on node 14: https://github.com/winstonjs/winston/issues/1797

```
│ Human Made Tachyon in node
│ git+https://github.com/humanmade/node-tachyon.git
│ https://github.com/humanmade/node-tachyon#readme
└─┬ aws-xray-sdk-core@2.4.0
  │ AWS X-Ray SDK for Javascript
  │ https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core
  └── winston@2.4.4
      A multi-transport async logging library for Node.js
      git+https://github.com/winstonjs/winston.git
      https://github.com/winstonjs/winston#readme
```

Winston throws out `(node:26972) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency` which is logged as an error in AWS Lambda (and trigger alarms if there are set in CloudWatch).

Later version of `aws-xray-sdk-node` removes dependency on `winston` which should resolve this issue.

## Acceptance Criteria
- [x] `aws-xray-sdk-node` has to be updated to the latest version that supports Node 14.x
- [x] Code that uses `aws-xray-sdk-node` still works as expected

**Comment by jerico** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/tachyon/148?planning-poker) with ZenHub @kovshenin @ferschubert-hm @wisyhambolu @mikelittle

**Comment by veselala** [comment]
@ferschubert-hm @mikelittle we've estimated this one to 3SP and moved it to the Backlog

**Comment by wisyhambolu** [comment]
After this [PR](https://github.com/humanmade/tachyon/pull/149) is reviewed and merged, I'll push the docker image version `2.6.0` to docker hub.

**Comment by wisyhambolu** [comment]
Created new release v2.6.1 for Tachyon which in turn created a [v2.6.1](https://hub.docker.com/layers/tachyon/humanmade/tachyon/v2.6.1/images/sha256-f52223adb0e6b1befa1782bae0f891a72146743dab8e79cffd3ef6ff4fffafbb?context=explore) image on dockerhub

**Comment by wisyhambolu** [comment]
Created new release v2.6.1 for Tachyon which in turn created a [v2.6.1](https://hub.docker.com/layers/tachyon/humanmade/tachyon/v2.6.1/images/sha256-f52223adb0e6b1befa1782bae0f891a72146743dab8e79cffd3ef6ff4fffafbb?context=explore) image on dockerhub
