### ISSUE TITLE
Document non JPG/PNG format handling

### ISSUE THREAD

**Issue by svandragt** [humanmade/tachyon#153]
Couldn't find in the documentation. Noticed [in the code](https://github.com/humanmade/tachyon/search?q=gif) that GIF is returned as is.

Perhaps a good place for the docs is https://docs.altis-dxp.com/media/dynamic-images/, maybe also document it on this repo.

**Comment by joehoyle** [comment]
This is fixed in #162 as we now support GIF image resizing.
