### ISSUE TITLE
Q: Licensing model

### ISSUE THREAD

**Issue by sonecabr** [humanmade/tachyon#159]
Hi there, first of all thanks for the great project. Apologies if it's already noted in the repository, but I hope it's okay to ask. Is there a Licensing model defined for this project? I see you guys use `Sharp` which is Apache 2.0, is it the case for your project as well?

Kind Regards

**Comment by sonecabr** [comment]
I just noticed [this](https://github.com/humanmade/tachyon/issues/70) closed issue, but seems closed without defining the License type.

**Comment by joehoyle** [comment]
sorry looks like #70 was erroneously closed, I've re-opened it. Closing _this_ issue in favor of #70
