### ISSUE TITLE
Node 18 support?

### ISSUE THREAD

**Issue by EffakT** [humanmade/tachyon#166]
I see that the cloudformation templates uses node10, however we have managed to get this running on Node16 without any trouble.

Node16 is LTS until March 11 2024.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

Is there any plan to update Tachyon to support AWS-SDK v3 which is required to use the node18 runtime.

**Comment by Arrig0** [comment]
I successfully updated the package.json to work with node 18.4.
Not yet tested on AWS (the node engine in the cloudformation-template.json file should be updated).
Here are the updated package.json dependencies:
`
"dependencies": {
    "animated-gif-detector": "^1.2.0",
    "imagemin-pngquant": "^8.0.0",
    "sharp": "^0.32.5",
    "smartcrop-sharp": "^2.0.8"
  },
  "devDependencies": {
    "aws-sdk": "^2.276.1",
    "aws-xray-sdk-core": "^2.4.0",
    "cli-table": "^0.3.1",
    "filesize": "^4.1.2"
  }
`

**Comment by EffakT** [comment]
Yep, the main issue that I found was the requirement for AWS SDK v3 when using Lambda.
This seems to be quite a rework, moving to async functions, removal of the makeUnauthenticatedRequest function, etc.

**Comment by Arrig0** [comment]
ok, I understand what you're saying.
I join your question about upgrading to aws-sdk v3.
In the meantime I'll try to make some attempts.

**Comment by joehoyle** [comment]
This was done in #162
