### ISSUE TITLE
pngquant is no longer needed

### ISSUE THREAD

**Issue by johnbillion** [humanmade/tachyon#167]
Tachyon uses pngquant to compress PNG files, but this hasn't been needed since Sharp 0.28 which includes built-in support for generating compressed palette PNGs.

Ref: https://github.com/lovell/sharp/issues/478#issuecomment-847150787

This means the separate pngquant processing in Tachyon could be replaced with the `palette` argument for Sharp.

**Comment by joehoyle** [comment]
Nice find @johnbillion !
