### ISSUE TITLE
Rename to tachyon

### ISSUE THREAD

**Issue by rmccue** [humanmade/tachyon#22]
We don't use the main tachyon repo any more, so we should rename that to tachyon-php and this one to tachyon to simplify the URLs.

**Comment by rmccue** [comment]
@joehoyle Any forseeable problems with this? Are we relying on the existing URLs anywhere that wouldn't handle the GitHub redirect?

**Comment by joehoyle** [comment]
Should be fine, as we upload a build for Lambda to use on S3.

**Comment by joehoyle** [comment]
Done!
