### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by danharper83** [humanmade/tachyon#28]
Hi,

I've been trying to deploy this but I'm running to issues where the image returned is a 2x2 pixel image regardless of what I try.

I've cloned master and run NPM inside an AWS environment using node 4.3.1 and then deployed using an S3 bucket

example here
http://d3moonnr9fkxfg.cloudfront.net/uploads/2017/05/coverthumb.jpg?w=500&h=500

Any help would be appreciated.

Cheers Dan

**Comment by joehoyle** [comment]
Aha, as it happens I think I know what this is! There's currently a limitation in the CloudFormation template where it's not possible to set Binary Types for API Gateway, so this needs to be done manually. Sorry for that not being part of the docs, we need to add that!

1. Go to the API Gateway Console https://console.aws.amazon.com/apigateway/home (select your region as necessary)
1. Select Tachyon on the left under APIs
1. Select "Binary Support" in the submenu.
1. Click Edit on the right hand side ![](http://joehoyle-captured.s3.amazonaws.com/J5G6zIOh.png)
1. Enter `image/*` in the Binary Media Types ![](http://joehoyle-captured.s3.amazonaws.com/S0rgHql5.png)
1. Click Save
1. Select the Resources under the Tachyon menu on the left ![](http://joehoyle-captured.s3.amazonaws.com/htRaf5pN.png)
1. Select Deploy API from the Actions dropdown ![](http://joehoyle-captured.s3.amazonaws.com/KuRarh28.png)
1. Select Prod from the Deployment Stage dropdown ![](http://joehoyle-captured.s3.amazonaws.com/aVHihHyV.png)
1. Click Deploy

Wait 30 seconds and try a new URL request, like `http://d3moonnr9fkxfg.cloudfront.net/uploads/2017/05/coverthumb.jpg?w=500&h=499` to bust the CloudFront cache.

If that works, you'll then want to invalidate all items in the CloudFront cache.

**Comment by danharper83** [comment]
Great, the bit I was missing was re-deploying the API it's all working now.
