### ISSUE TITLE
Support for images without a query string

### ISSUE THREAD

**Issue by jamesmorrison** [humanmade/tachyon#29]
Firstly, many thanks for releasing this publicly; I believe this is revolutionary in the context of dealing with images in WordPress.

I've noticed that images without a query string return an "internal server error" message rather than an image; for example: https://us-east-1.tchyn.io/humanmade-production/uploads/2017/04/ustwo.jpg?w=870 vs https://us-east-1.tchyn.io/humanmade-production/uploads/2017/04/ustwo.jpg

Would it be possible to adjust the functionality to make the query string optional, and serve the image at the original resolution where one isn't specified?

**Comment by rmccue** [comment]
I think we noticed this just prior to publishing; totally a bug, and we should fix it.

@joehoyle Did you find out why it was erroring?

**Comment by joehoyle** [comment]
This should be fixed #30
