### ISSUE TITLE
Handle paths with percent encoding

### ISSUE THREAD

**Issue by binuks** [humanmade/tachyon#32]
When Tachyon gets paths with percent encoding, it looks up the S3 bucket without converting encoded characters. They key with the percent encoding is not found in the bucket.

Tachyon should decode the path before looking up S3.

**Comment by joehoyle** [comment]
Hmm I thought this would have been fixed with https://github.com/humanmade/tachyon/commit/a905085805e23e6fb8b7c63a4205e1c234df3af1 are you running the release past that commit?

**Comment by binuks** [comment]
We are not using a lambda deployment. I do see a decodeURI call in server.js as well. I'll investigate further to check why the S3 key does not match.

**Comment by binuks** [comment]
The path in question had an '@' character that was encoded as %40 by Wordpress. decodeURI does not unescape this, decodeURIComponent does.

**Comment by rmccue** [comment]
We're hitting this on humanmade.com with some stuff.

**Comment by roborourke** [comment]
I think this one is fully resolved now. Not seen it happen or any reports of it for some time. We can reopen if that’s not the case
