### ISSUE TITLE
Support for WebP

### ISSUE THREAD

**Issue by joehoyle** [humanmade/tachyon#39]
This has been tricky as it's then difficult to cache at the CDN level as you need to vary based off the Accept header, which is a _huge_ amount of values that basically make the cache worthless. 

I *think* we can actually do this with Lamdba @Edge though, more to come!

**Comment by roborourke** [comment]
Looks like this is done?

**Comment by roborourke** [comment]
Going to close this out for now as we can pass `webp=1` in the query params.

**Comment by joehoyle** [comment]
Webp auto detection is then done at the cDN level using a lambda@edge function, which passes webp=1. That query param should typically never be used directly

**Comment by roborourke** [comment]
Ah, cheers for clarifying 👍
