### ISSUE TITLE
It would be useful to have ability to embed on a background

### ISSUE THREAD

**Issue by stevegibbings** [humanmade/tachyon#42]
I've found that we often want an image to result in an exact size even if the resized image would be less than the requested size. Sharp has a `embed()` function that works similar to max but fills in the background out to the requested dimensions.

I've created a PR that adds this

https://github.com/humanmade/tachyon/pull/41

**Comment by stevegibbings** [comment]
Proposed solution now on https://github.com/humanmade/tachyon/pull/44

**Comment by stevegibbings** [comment]
Thanks for accepting #45 @joehoyle

**Comment by joehoyle** [comment]
Thanks so much!
