### ISSUE TITLE
Cloud Formation Template Has Errors

### ISSUE THREAD

**Issue by kingkool68** [humanmade/tachyon#48]
The `LambdaFunction` key has two "Handler" properties.  I think the line `"Handler": "index.handler",` can be deleted. 

I ended up having to reconstruct my own to get everything up and running.

**Comment by joehoyle** [comment]
Good catch! Oddly this doesn't actually trigger a CF error for me though, is it a JSON parsing error you get?

**Comment by kingkool68** [comment]
I tried loading it in the CloudFormation designer thingy and it didn't validate.

**Comment by kingkool68** [comment]
Nevermind I think you're right, it was probably a JSON parsing error. I copy and pasted the Cloud Formation template the first time. Just now I uploaded the file directly to the Cloud Formation designer and it seems to work just fine.
