### ISSUE TITLE
Add documentation for certificate region requirement

### ISSUE THREAD

**Issue by garrettjohnson** [humanmade/tachyon#49]
In the [server setup notes](https://engineering.hmn.md/projects/tachyon/server/) for AWS CloudFormation, it would be helpful to include a note that certificates must be created/imported in the `us-east-1` region or setup will fail.

**Comment by rmccue** [comment]
Good catch, I'll update those docs now!

**Comment by rmccue** [comment]
This is now sorted; thanks! 🎄
