### ISSUE TITLE
Smart cropping options

### ISSUE THREAD

**Issue by roborourke** [humanmade/tachyon#54]
Proposing 3 new values that can be set as the `crop` argument:

- `?crop=attention`: uses sharp's built in `attention` cropping strategy
- `?crop=entropy`: uses sharp's built in Shannon `entropy` cropping strategy
- `?crop=smart`: use the [smartcrop](https://github.com/jwagner/smartcrop-sharp) library - this might make a good default setting too.

How does the above sound @rmccue ?

**Comment by rmccue** [comment]
I’d keep the default the same, to ensure it’s predictable (even if not the “best”).

**Comment by roborourke** [comment]
The linked PR works pretty well. I did some benchmarking using seige:

```
siege -b -t 10S -c 10 https://vagrant.local/tchyn/uploads/image.jpg
```

The following are the average results of 5 runs on each type of cropping, accuracy of crop is subjective based on a selection of images I tried out.

| strategy | hits | accuracy of crop |
|---|---|---|
| none | 105 | - |
| entropy | 70 | mediocre | 
| attention | 28 | good |
| smart | 46 | very good |
