### ISSUE TITLE
Add face detection boost to improve smart cropping

### ISSUE THREAD

**Issue by roborourke** [humanmade/tachyon#60]
The [smartcrop.js](https://github.com/jwagner/smartcrop.js/#boost) library gets decent results a lot of the time but can be helped by providing areas of an image to 'boost'.

The examples on the website suggest a few libraries for face detaction but they're all client side libraries that rely on the DOM & canvas.

We could use [node-opencv](https://github.com/peterbraden/node-opencv) to run it against the basic face cascade as an initial experiment.

**Comment by joehoyle** [comment]
Closing this as it's not been majorly requested
