### ISSUE TITLE
Does Tachyon Support Digital Ocean Spaces and on Digital Ocean Droplets?

### ISSUE THREAD

**Issue by xianx** [humanmade/tachyon#63]
I am trying to use tachyon with Digital Ocean Spaces and on Digital Ocean Droplets will it work?

**Comment by rmccue** [comment]
Tachyon is primarily built for Lambda, so we don't officially support any other environment. That said, Tachyon can run as a standalone Node tool, you'll just need to write your own [connector code](https://github.com/humanmade/tachyon/blob/master/lambda-handler.js).

**Comment by xianx** [comment]
but the docker version isnt made for work without lamda? https://hub.docker.com/r/humanmade/tachyon/ and isnt the docker version run and resize without the lamda connector code?

**Comment by rmccue** [comment]
The Docker version is primarily designed to aid local usage and development rather than production use, and we don't use it in production. We're happy to merge PRs if you find problems with it, but it is not maintained at the same level as the Lambda setup. :)

**Comment by xianx** [comment]
but can the docker version be used for production?

**Comment by xianx** [comment]
okay I have successful on standalone nodejs install with a nginx proxy in front of it. 

Now working nice http://t-tunes-rnc-www.iydaiquy4.at.d2c.io/artboard.png?h=100

1. is the server.js is maintained?
2. Can standalone node version be used for production? I know there server resource require. but is the node app itself can be run on production?
3. How can I serve the image with cdn? cahe the image and serve images from cache?
4. Is it possible to save the resulted image to save on server?

Thanks.

**Comment by xianx** [comment]
@rmccue can I get the answers of above questions? (The test server has destroyed) but please let me know the answers.
