### ISSUE TITLE
What is tachyon's license?

### ISSUE THREAD

**Issue by PandelisZ** [humanmade/tachyon#70]
Whats the license for tachyon itself? I might need to extend it a little to fit it into our workflow and would like to know how much of the source I need to keep public :) Thanks for the awesome work! 

(Obv I'll contribute back all I can!)

**Comment by rmccue** [comment]
According to [license-checker](https://www.npmjs.com/package/license-checker):
```
├─ MIT: 50
├─ ISC: 19
├─ BSD-3-Clause: 4
├─ Apache-2.0: 3
├─ MIT*: 1
└─ Apache 2.0: 1
```

As far as I know, the code in Tachyon is not derived from any other source, so I'd say we should specify the licence as ISC; @joehoyle?

@PandelisZ In any case, we wouldn't use something like AGPL or require publishing changes. GPL is possible, but you'd still be able to keep your alterations private.

**Comment by joehoyle** [comment]
ISC sounds fine to me
