### ISSUE TITLE
Add watermark support

### ISSUE THREAD

**Issue by roborourke** [humanmade/tachyon#72]
This is something sharp can do pretty easily.

Suggested API:

```
?wm=/path/to/image.png,southeast
```

Whereby the S3 path is the first arg and after the comma is the position which could default to bottom right.

**Comment by alsguimaraes** [comment]
Probably best if a default wm could be on config, so wm=default or wm=true would use that.
I suspect that most use cases would apply the same watermark.
That could be loaded on a buffer upon container initialization and reused.

**Comment by roborourke** [comment]
That's a good idea, thanks. There's a use-case where you might want to generate or create different branded versions of an image on the fly for different situations on a website such as a hero image vs a post thumbnail for instance.

**Comment by joehoyle** [comment]
I'm going to close this as wontfix until some future time when this is more required
