### ISSUE TITLE
Large PNG image error

### ISSUE THREAD

**Issue by gblakeman** [humanmade/tachyon#76]
It seems like a large image (PNG file > `2000x2000 px`) is causing an error: `{"message": "Internal server error"}`.

I’ve tried increasing the Lambda memory allocation but it hasn’t worked. Any other ideas how I might troubleshoot the issue?

**Comment by tedyw** [comment]
It seems that the chosen node sharp version can’t transform high-res pngs properly, leading to blown up file sizes which lambda refuse to serve (check for “body size too long” in cloud watch). The limit is 6MB if I remember correctly. Ended up modifying the lambda handler to use imagemin-pngquant when dealing with pngs.

**Comment by gblakeman** [comment]
@tedyw Ha, that make sense. I’d noticed the biggest PNG I could generate was just under 6mb. Thanks for the tip!

**Comment by roborourke** [comment]
@tedyw do you have a fork we could look at? Sounds like something it'd be good to fix.

I'm hoping to get sharp updated soon as well but there's a breaking change related to webp that's blocking us right now.

**Comment by roborourke** [comment]
Updated sharp but still seeing PNGs getting inflated size wise. Trying to understand why but looks like the imagemin solution might be necessary after all

**Comment by joemcgill** [comment]
This can often happen whenever a PNG is resampled. Essentially, whenever you resize a PNG, there is antialiasing that occurs, which introduced new colors to the image and increases the overall size.

See https://core.trac.wordpress.org/ticket/30402#comment:4 for more conversation about this problem.

**Comment by ShinichiNishikawa** [comment]
I am not sure if it’s related but FujiTV had this internal server error with this image: https://www.fujitv-view.jp/tachyon/2019/11/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88-2019-11-11-14.16.37.png?fit=2148,1388

**Comment by joehoyle** [comment]
This is the description of why Sharp produces large PNG files: https://github.com/lovell/sharp/issues/478/ I think we should add pngquant or the wrapper imagemin (so we can handle other compressions in the future). https://github.com/imagemin/imagemin looks like a good option, though depends on the install size, as we are getting close to the 50MB zip file limit.

**Comment by joehoyle** [comment]
This is in v2.2,0-beta2
